<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>free-icon-ruble-1868089.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="free-icon-ruble-1868089.ico" />
  </ItemGroup>

</Project>